name: Monthly Update

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xlsx2csv

    - name: Run make
      run: make
